FROM node:20
ARG GITHUB_SERVER_URL
ENV GITHUB_SERVER_URL=${GITHUB_SERVER_URL}
ARG GITHUB_REPOSITORY
ENV GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
ARG GITHUB_SHA
ENV GITHUB_SHA=${GITHUB_SHA}
RUN mkdir -p /srv
WORKDIR /srv
COPY . .
RUN npm ci
EXPOSE 3000
CMD ["npm", "run", "listen"]